Feature/paging
Architect-Coders-Team-2/ArquitectoMarvel pull request #48
Opened 2021-05-02 11:09 UTC by joseantoniocampillo

**ISSUE**
#28

**SUMMARY**
Add Pagin in principal list, and propuse light changes for UI style.

**CHANGES MADE**

Add Paging support with Paging 3 library.
Add extra with a LoadStateAdapter.
Little change on colors in styles.

2021-05-02 15:19 UTC, juancoob requested changes
Thanks @joseantoniocampillo Please, check my comments and let me know what do you think.

2021-05-02 15:19 UTC, juancoob commented on app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.2'
@joseantoniocampillo Why we do need the alpha version of retrofit?

2021-05-02 15:19 UTC, juancoob commented on app/src/main/java/com/architectcoders/arquitectomarvel/ui/main/AdapterList.kt
> +const val INICIAL = 36
@joseantoniocampillo can you change the variable name to "STARTING"?

2021-05-02 15:19 UTC, juancoob commented on app/src/main/java/com/architectcoders/arquitectomarvel/ui/main/AdapterList.kt
> +//                prevKey = if (offset == INICIAL) null else offset + INICIAL,
@joseantoniocampillo is this line necessary?

2021-05-02 15:19 UTC, juancoob commented on app/src/main/java/com/architectcoders/arquitectomarvel/ui/main/MainActivity.kt
> +                        3
@joseantoniocampillo could you explain why this is necessary?

2021-05-02 15:19 UTC, juancoob commented on app/src/main/java/com/architectcoders/arquitectomarvel/ui/main/MainViewModel.kt
> +//            maxSize = 54,
@joseantoniocampillo is this line needed? Should we store the numbers like "pageSize" on dimens.xml?

2021-05-02 19:05 UTC, juancoob approved these changes
Perfect @joseantoniocampillo !!

2021-05-03 08:15 UTC, jujoru approved these changes
OK¡

2021-05-03 20:34 UTC, JorgeGreek approved these changes
perfect

2021-05-04 05:43 UTC, merged