Feature/jorge/clean
Architect-Coders-Team-2/ArquitectoMarvel pull request #58
Opened 2021-05-16 07:36 UTC by JorgeGreek

2021-05-16 16:13 UTC, juancoob requested changes
@JorgeGreek thanks! Could you check my comments?

2021-05-16 16:13 UTC, juancoob commented on app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.2'
@JorgeGreek why do we need the alpha version?

2021-05-16 16:13 UTC, juancoob commented on app/src/main/java/com/architectcoders/arquitectomarvel/model/database/ResultDao.kt
> +//    suspend fun getCharacters(): List<CharacterEntity>
@JorgeGreek could you remove the commented code?

2021-05-16 16:13 UTC, juancoob commented on data/build.gradle
> +    sourceCompatibility = JavaVersion.VERSION_1_7
@JorgeGreek could you update the java version?

2021-05-16 16:13 UTC, juancoob commented on domain/build.gradle
> +    sourceCompatibility = JavaVersion.VERSION_1_7
@JorgeGreek could you update the java version?

2021-05-16 16:13 UTC, juancoob commented on usecase/build.gradle
> +    sourceCompatibility = JavaVersion.VERSION_1_7
@JorgeGreek could you update the java version?

2021-05-16 16:13 UTC, juancoob commented on usecase/src/main/java/com/architectcoders/usecase/MyClass.kt
> +class MyClass {
@JorgeGreek could you delete this class?

2021-05-17 12:31 UTC, juancoob approved these changes
Cool @JorgeGreek !! Thanks!

2021-05-24 04:17 UTC, joseantoniocampillo approved these changes
That's ok

2021-05-29 18:54 UTC, merged