Feature/juan/integration testing
Architect-Coders-Team-2/ArquitectoMarvel pull request #93
Opened 2021-09-10 12:50 UTC by juancoob

**ISSUE**
#83 

**SUMMARY**
Add instrumentation tests to the app. Despite _FavoriteCharacterViewModelIntegrationTest_ and _CharacterDetailViewModelIntegrationTest_ are both not necessary, they were added just for practice purposes

2021-10-03 20:50 UTC, joseantoniocampillo requested changes
For integration tests I would consider providing an in-memory roomdatabase with:
Room.inMemoryDatabaseBuilder.

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    var pwd: String = "pwd"
This value can be Null in production and it should be Nullable anyway for test

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    var hint: String = "hint"
(Idem)

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    var fakeCharacterList: MutableList<Character> = mutableListOf()
I think you would have to fill a fakeList here and then interact with it through the methods of this implementation of the localdatasource ...

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    override suspend fun getLocalCharactersCount(): Int = 1
This must be:
 = fakeCharacterList.size

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    override suspend fun getLocalCharacterById(characterId: Int): Character = mockedCharacter
this must be:
```
override suspend fun getLocalCharacterById(characterId: Int): Character? =      
        fakeCharacterList.find { it.id == characterId }
```
So we need change in LocalDataSource interface for this in its function:
suspend fun getLocalCharacterById(characterId: Int): Character?
(Making it with a nullable return)

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +        pwd = ""
I think the pwd and hint class variables should be set to null

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    override fun isLocalCharacterFavorite(characterId: Int): Any = flowOf(1)
maybe better:
```
flowOf(
    fakeFavoriteCharacterList.find { it.id == characterId }?:0
)
```

2021-10-03 20:50 UTC, joseantoniocampillo commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/integration/MainViewModelIntegrationTest.kt
> +        mainViewModel.checkIfPasswordIsCorrect("") {
It does not correspond to production.
deleteCredentials, implies that checkIfPasswordIsCorrect ("") is currently crashing the app. Review it.

2021-10-05 08:12 UTC, juancoob commented
> For integration tests I would consider providing an in-memory roomdatabase with: Room.inMemoryDatabaseBuilder.

Hello @joseantoniocampillo but this approach uses fakes instead of real data, so that's why I don't use it

2021-10-05 08:18 UTC, juancoob commented on app/src/androidTest/java/com/architectcoders/arquitectomarvel/fakeDataSources/FakeLocalDataSource.kt
> +    var pwd: String = "pwd"
You are right @joseantoniocampillo ! I'll change it :smile:

2021-10-07 19:55 UTC, jujoru approved these changes
Ok

2021-10-07 20:11 UTC, JorgeGreek approved these changes
ok

2021-10-08 13:14 UTC, joseantoniocampillo approved these changes
That's good

2021-10-09 11:29 UTC, merged